development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample_app
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
  host: localhost
  
production:
  adapter: postgresql
  encoding: utf8
  database: sample_app
  pool: 5
  username: root
  password:

  